replicaCount: 1
image:
  repository: ghaitho20/go-web-app
  pullPolicy: IfNotPresent 
  tag: "15695215504"
ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific 
